
import sys, csv

# Name
# Release data / download date / version
# Number of taxon records in source (terminal only?)
# Number of taxon records used in Open Tree
# Number of taxon records used in Open Tree that are binomials ?
# Number of synonym records used in Open Tree
# Priority
# Reference number(s) - full reference in article's reference list
# Maximum depth

properties = [
    {'name': 'separation taxa',
     'reference': '',
     'version': '4b3ba1a',
     'priority': 1,
     'focus': 'life',
     'taxa': 29,
     'synonyms': 8,
     'goals': ''},
    {'name': 'ARB-SILVA',
     'reference': '[ref 10.1093/nar/gks1219]',
     'version' : '115',
     'priority': 2,
     'focus': 'life',
     'taxa': 78687,
     'synonyms': 0,
     'goals': 'P'},
    {'name': 'Hibbett 2007',
     'reference': '[ref gazis2015]',
     'version' : 'v4',
     'priority': 3,
     'focus': 'Fungi',
     'taxa': 227,
     'synonyms': 0,
     'goals': 'P'},
    {'name': 'Index Fungorum',
     'reference': '[ref fungorum2014]',
     'version' : '2014-04-07',
     'priority': 4,
     'focus': 'Fungi',
     'taxa': 284973,
     'synonyms': 157734,
     'goals': 'P,T'},
    {'name': 'Sch&auml;ferhoff 2010',
     'reference': '[ref 10.1186/1471-2148-10-352]',
     'version' : '2010-11-12',
     'priority': 5,
     'focus': 'Lamiales',
     'taxa': 119,
     'synonyms': 0,
     'goals': 'P'},
    {'name': 'WoRMS',
     'reference': '[ref worms2015]',
     'version' : '2015-10-01',
     'priority': 6,
     'focus': 'Malacostraca, Cnidaria',
     'taxa': 330412,
     'synonyms': 223196,
     'goals': 'P,T'},
    {'name': 'NCBI',
     'reference': '[ref ncbi2016]',
     'version' : '2016-11-09',
     'priority': 7,
     'focus': 'life',
     # These numbers come from running process_ncbi_taxonomy.py.
     # Need to review - names.dmp seems to have 2207998 rows, much bigger
     # (some of those will be authorities, etc.)
     # (+ 1488029 404511)
     'taxa': 1488029,   # Boils down to 1488019
     'synonyms': 719526,
     'goals': 'O,P,T'},  # Careful about how to count.
    {'name': 'GBIF',
     'reference': '[ref gbifbackbone2016]',
     'version' : '2016-07-29',
     'priority': 8,
     'focus': 'life',
     # These numbers come from running process_gbif_taxonomy.py on the 2013 version
     'taxa': 3273321,     # Boils down to 1863834
     'synonyms': 1143026,
     'goals': 'T'},  # Boils down to 879745
    {'name': 'IRMNG',
     'reference': '[ref irmng2014]',
     'version' : '2014-01-31',
     'priority': 9,
     'focus': 'life',
     # These numbers come from running process_irmng.py, I believe
     'taxa': 1706655,    # Boils down to 1685134
     'synonyms': 685983,
     'goals': 'T'}, # Boils down to 659851
    {'name': 'Open Tree curation',
     'reference': '',
     'version': '4b3ba1a',
     'priority': 10,
     'focus': '',
     'taxa': 'xx',
     'synonyms': 0,
     'goals': 'O'}
]

header = ['name', 'reference',
          #'version',   #Removed at KC's request
          'focus', 'taxa', 'synonyms', 'priority', 'reasons']

table = []
table.append(header)

for plist in properties:
    table.append([plist['name'], plist['reference'],
                  #plist['version'],
                  plist['focus'], plist['taxa'], plist['synonyms'], plist['priority'], plist['goals']])


def show_table_csv(table):
    print
    print '```'
    writer = csv.writer(sys.stdout, lineterminator='  \n')
    for row in table:
        writer.writerow(row)
    print '```'

def show_table_html(table):
    print '<table>'
    for row in table:
        do_row(row)
    print '</table>'

def do_row(cells):
    print '  <tr>'
    for val in cells:
        cell(val)
    print '  </tr>'

def cell(val):
    print '    <td>'
    print '   ', val
    print '    </td>'


print '<!--**** THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT ****-->'
print '### (Table 1)'

show_table_html(table)
show_table_csv(table)

print
print """[JAR: get final curation counts.  `cat amendments/*.json | grep original_label | wc` plus `grep "^add" feed/ott/edits/*.tsv | wc`]"""

"""

Maybe put number of binomials in the table?

    silva,13953
    if,237482
    worms,258378
    ncbi,360455
    gbif,1629523
    irmng,1111550
    curation,15

Maybe some measure of resolution, like maximum depth?

end table]
"""
