#!/bin/bash

# Modify as appropriate to your own hardware
JAVAFLAGS="-Xmx14G"
CLASSPATH="..:../lib/json-simple-1.1.1.jar"
JAVA="java ${JAVAFLAGS} -classpath ${CLASSPATH}"

if [ $1x = "testx" ]; then
  # Use this version for testing
  ${JAVA} org.opentreeoflife.server.Services ../registry/aster-ott29 ../registry/aster-synth4/
else

  # Use this version for real (takes a while to load up)

  # Set up symbolic links if these things don't already exist locally

  if [ ! -e ott ]; then
    echo Getting OTT
    wget http://files.opentreeoflife.org/ott/ott2.9/ott2.9.tgz
    tar xzf ott2.9.tgz
  fi

  if [ ! -e draftversion4.tre ]; then
    if [ ! -e draftversion4.tre.gz ]; then
      echo Getting synthetic tree
      wget http://files.opentreeoflife.org/trees/draftversion4.tre.gz
    fi
    gunzip draftversion4.tre.gz
  fi

  ${JAVA} org.opentreeoflife.server.Services ott/ draftversion4.tre

fi
